# EDA - All
* 이 커널에서는 모든 피처를 하나하나씩 살펴보며 어떤 데이터 양상을 띄고 있는 지 검토할 것입니다.

## 라이브러리

In [1]:
import numpy as np
import pandas as pd
import warnings
import gc
warnings.filterwarnings("ignore")

In [2]:
pd.set_option('max_rows', 150)
pd.set_option('max_colwidth', 500)
pd.set_option('max_columns', 500)

## 데이터 로드

In [3]:
dtypes = {
        'MachineIdentifier':                                    'object',
        'ProductName':                                          'category',
        'EngineVersion':                                        'category',
        'AppVersion':                                           'category',
        'AvSigVersion':                                         'category',
        'IsBeta':                                               'int8',
        'RtpStateBitfield':                                     'float16',
        'IsSxsPassiveMode':                                     'int8',
        'DefaultBrowsersIdentifier':                            'float16',
        'AVProductStatesIdentifier':                            'float32',
        'AVProductsInstalled':                                  'float16',
        'AVProductsEnabled':                                    'float16',
        'HasTpm':                                               'int8',
        'CountryIdentifier':                                    'int16',
        'CityIdentifier':                                       'float32',
        'OrganizationIdentifier':                               'float16',
        'GeoNameIdentifier':                                    'float16',
        'LocaleEnglishNameIdentifier':                          'int8',
        'Platform':                                             'category',
        'Processor':                                            'category',
        'OsVer':                                                'category',
        'OsBuild':                                              'int16',
        'OsSuite':                                              'int16',
        'OsPlatformSubRelease':                                 'category',
        'OsBuildLab':                                           'category',
        'SkuEdition':                                           'category',
        'IsProtected':                                          'float16',
        'AutoSampleOptIn':                                      'int8',
        'PuaMode':                                              'category',
        'SMode':                                                'float16',
        'IeVerIdentifier':                                      'float16',
        'SmartScreen':                                          'category',
        'Firewall':                                             'float16',
        'UacLuaenable':                                         'float32',
        'Census_MDC2FormFactor':                                'category',
        'Census_DeviceFamily':                                  'category',
        'Census_OEMNameIdentifier':                             'float16',
        'Census_OEMModelIdentifier':                            'float32',
        'Census_ProcessorCoreCount':                            'float16',
        'Census_ProcessorManufacturerIdentifier':               'float16',
        'Census_ProcessorModelIdentifier':                      'float16',
        'Census_ProcessorClass':                                'category',
        'Census_PrimaryDiskTotalCapacity':                      'float32',
        'Census_PrimaryDiskTypeName':                           'category',
        'Census_SystemVolumeTotalCapacity':                     'float32',
        'Census_HasOpticalDiskDrive':                           'int8',
        'Census_TotalPhysicalRAM':                              'float32',
        'Census_ChassisTypeName':                               'category',
        'Census_InternalPrimaryDiagonalDisplaySizeInInches':    'float16',
        'Census_InternalPrimaryDisplayResolutionHorizontal':    'float16',
        'Census_InternalPrimaryDisplayResolutionVertical':      'float16',
        'Census_PowerPlatformRoleName':                         'category',
        'Census_InternalBatteryType':                           'category',
        'Census_InternalBatteryNumberOfCharges':                'float32',
        'Census_OSVersion':                                     'category',
        'Census_OSArchitecture':                                'category',
        'Census_OSBranch':                                      'category',
        'Census_OSBuildNumber':                                 'int16',
        'Census_OSBuildRevision':                               'int32',
        'Census_OSEdition':                                     'category',
        'Census_OSSkuName':                                     'category',
        'Census_OSInstallTypeName':                             'category',
        'Census_OSInstallLanguageIdentifier':                   'float16',
        'Census_OSUILocaleIdentifier':                          'int16',
        'Census_OSWUAutoUpdateOptionsName':                     'category',
        'Census_IsPortableOperatingSystem':                     'int8',
        'Census_GenuineStateName':                              'category',
        'Census_ActivationChannel':                             'category',
        'Census_IsFlightingInternal':                           'float16',
        'Census_IsFlightsDisabled':                             'float16',
        'Census_FlightRing':                                    'category',
        'Census_ThresholdOptIn':                                'float16',
        'Census_FirmwareManufacturerIdentifier':                'float16',
        'Census_FirmwareVersionIdentifier':                     'float32',
        'Census_IsSecureBootEnabled':                           'int8',
        'Census_IsWIMBootEnabled':                              'float16',
        'Census_IsVirtualDevice':                               'float16',
        'Census_IsTouchEnabled':                                'int8',
        'Census_IsPenCapable':                                  'int8',
        'Census_IsAlwaysOnAlwaysConnectedCapable':              'float16',
        'Wdft_IsGamer':                                         'float16',
        'Wdft_RegionIdentifier':                                'float16',
        'HasDetections':                                        'int8'
        }

In [4]:
train = pd.read_csv('./data/train.csv', dtype=dtypes)
test = pd.read_csv('./data/test.csv', dtype=dtypes)

## 컬럼 분석

### Census_OSInstallLanguageIdentifier

In [84]:
col = 'Census_OSInstallLanguageIdentifier'

In [85]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

       Census_OSInstallLanguageIdentifier   rate
 8.0                              3179262  35.64
 9.0                              1034201  11.59
 7.0                               512753   5.75
 29.0                              492267   5.52
 14.0                              432503   4.85
 37.0                              403190   4.52
 10.0                              366636   4.11
 26.0                              334766   3.75
 5.0                               252887   2.83
 35.0                              204832   2.30
 39.0                              201525   2.26
 18.0                              190828   2.14
 20.0                              169059   1.89
 24.0                              142175   1.59
 25.0                              132408   1.48
 27.0                              108176   1.21
 19.0                               84177   0.94
 17.0                               83445   0.94
 1.0                                79777   0.89
 3.0                                72370   0.81
NaN                                 60084   0.67
 6.0                                50489   0.57
 33.0                               48800   0.55
 15.0                               41514   0.47
 4.0                                35407   0.40
 30.0                               31956   0.36
 23.0                               29496   0.33
 31.0                               22149   0.25
 12.0                               19906   0.22
 2.0                                18270   0.20
 16.0                               15831   0.18
 36.0                               14585   0.16
 28.0                               12696   0.14
 13.0                               10869   0.12
 34.0                               10647   0.12
 21.0                                6865   0.08
 32.0                                4559   0.05
 38.0                                3737   0.04
 11.0                                3219   0.04
 22.0                                3167   0.04

In [86]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

       Census_OSInstallLanguageIdentifier   rate
 8.0                              2805320  35.72
 9.0                               828830  10.55
 29.0                              543163   6.92
 37.0                              458146   5.83
 7.0                               423065   5.39
 14.0                              356466   4.54
 10.0                              320350   4.08
 26.0                              289091   3.68
 35.0                              200274   2.55
 5.0                               190338   2.42
 18.0                              164436   2.09
 20.0                              158416   2.02
 39.0                              154858   1.97
 25.0                              140231   1.79
 24.0                               98129   1.25
 27.0                               87155   1.11
 1.0                                77615   0.99
 17.0                               71324   0.91
 19.0                               64222   0.82
NaN                                 58743   0.75
 3.0                                56638   0.72
 6.0                                41246   0.53
 15.0                               33545   0.43
 33.0                               32272   0.41
 30.0                               25223   0.32
 4.0                                22665   0.29
 23.0                               19118   0.24
 31.0                               18348   0.23
 36.0                               17520   0.22
 2.0                                17510   0.22
 12.0                               16023   0.20
 16.0                               14075   0.18
 28.0                               12201   0.16
 34.0                               10409   0.13
 13.0                                8419   0.11
 21.0                                5703   0.07
 32.0                                4268   0.05
 11.0                                2807   0.04
 22.0                                2678   0.03
 38.0                                2413   0.03

In [87]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                                    HasDetections      cnt   rate
Census_OSInstallLanguageIdentifier
8.0                                     1612174.0  3179262  50.71
9.0                                      529033.0  1034201  51.15
29.0                                     249820.0   492267  50.75
7.0                                      249160.0   512753  48.59
37.0                                     208475.0   403190  51.71
14.0                                     203234.0   432503  46.99
10.0                                     197462.0   366636  53.86
26.0                                     170360.0   334766  50.89
5.0                                      111350.0   252887  44.03
35.0                                     106313.0   204832  51.90
39.0                                     101352.0   201525  50.29
18.0                                      92566.0   190828  48.51
20.0                                      81218.0   169059  48.04
24.0                                      66904.0   142175  47.06
25.0                                      63245.0   132408  47.77
27.0                                      53144.0   108176  49.13
17.0                                      45279.0    83445  54.26
1.0                                       38958.0    79777  48.83
19.0                                      36525.0    84177  43.39
3.0                                       32911.0    72370  45.48
6.0                                       23851.0    50489  47.24
15.0                                      21455.0    41514  51.68
33.0                                      20426.0    48800  41.86
4.0                                       14468.0    35407  40.86
30.0                                      14282.0    31956  44.69
31.0                                      11520.0    22149  52.01
23.0                                      11479.0    29496  38.92
2.0                                       10953.0    18270  59.95
36.0                                       8545.0    14585  58.59
16.0                                       7774.0    15831  49.11
12.0                                       7269.0    19906  36.52
28.0                                       5702.0    12696  44.91
34.0                                       5574.0    10647  52.35
13.0                                       5379.0    10869  49.49
21.0                                       3564.0     6865  51.92
32.0                                       2299.0     4559  50.43
38.0                                       1573.0     3737  42.09
22.0                                       1346.0     3167  42.50
11.0                                       1279.0     3219  39.73

### Census_OSUILocaleIdentifier

In [88]:
col = 'Census_OSUILocaleIdentifier'

In [89]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

     Census_OSUILocaleIdentifier   rate
31                       3170824  35.54
34                       1040042  11.66
30                        513995   5.76
125                       498236   5.58
49                        436691   4.89
158                       408118   4.57
35                        377071   4.23
119                       337988   3.79
26                        252863   2.83
148                       206854   2.32
160                       201983   2.26
72                        191930   2.15
83                        170681   1.91
109                       142479   1.60
115                       132758   1.49
120                       108817   1.22
64                         84426   0.95
74                         84458   0.95
5                          81845   0.92
20                         72672   0.81
28                         50797   0.57
140                        48933   0.55
58                         41994   0.47
24                         35558   0.40
128                        32294   0.36
105                        29567   0.33
130                        22721   0.25
44                         19963   0.22
11                         18618   0.21
62                         16130   0.18
151                        14903   0.17
123                        12860   0.14
145                        10779   0.12
48                         11113   0.12
156                         7726   0.09
90                          7206   0.08
136                         4629   0.05
68                          4615   0.05
159                         3917   0.04
92                          3450   0.04
38                          3340   0.04
17                          2171   0.02
55                             2   0.00
89                             3   0.00
13                             3   0.00
106                            3   0.00
99                             3   0.00
66                             3   0.00
87                             3   0.00
71                             3   0.00
150                            3   0.00
77                             4   0.00
82                             2   0.00
46                             3   0.00
138                            4   0.00
143                            4   0.00
153                            4   0.00
142                            4   0.00
81                             4   0.00
78                             4   0.00
41                             4   0.00
8                              4   0.00
25                             5   0.00
2                              5   0.00
16                             6   0.00
102                            6   0.00
85                             2   0.00
104                            1   0.00
3                              2   0.00
112                            2   0.00
43                             1   0.00
56                             1   0.00
57                             1   0.00
61                             1   0.00
67                             1   0.00
45                             8   0.00
52                             1   0.00
22                             1   0.00
113                            1   0.00
117                            1   0.00
18                             1   0.00
127                            1   0.00
108                            1   0.00
14                             1   0.00
155                            1   0.00
147                            1   0.00
144                            1   0.00
133                            2   0.00
86                             2   0.00
134                            2   0.00
96                             2   0.00
107                            2   0.00
10                             2   0.00
33                             7   0.00
27                            36   0.00
111                            8   0.00
9                              9   0.00
70                            49   0.00
91                            51   0.00
131                           52   0.00
63                            53   0.00
6                             58   0.00
93                            60   0.00
116                           64   0.00
121                           64   0.00
40                            67   0.00
146                           68   0.00
29                            68   0.00
36                            83   0.00
51                            83   0.00
157                           87   0.00
12                            98   0.00
37                           106   0.00
59                           161   0.00
161                          164   0.00
54                           170   0.00
15                           187   0.00
32                           207   0.00
126                          216   0.00
42                           286   0.00
73                            48   0.00
152                           48   0.00
7                             46   0.00
132                           27   0.00
135                           11   0.00
60                            13   0.00
139                           14   0.00
69                            14   0.00
98                            15   0.00
149                           18   0.00
141                           20   0.00
95                            22   0.00
39                            25   0.00
21                            27   0.00
124                           28   0.00
50                            44   0.00
80                            28   0.00
75                            28   0.00
19                            29   0.00
65                            33   0.00
122                           35   0.00
76                            36   0.00
110                           38   0.00
129                           42   0.00
84                            42   0.00
162                           42   0.00
1                              1   0.00

In [90]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

     Census_OSUILocaleIdentifier   rate
31                       2800526  35.66
34                        833576  10.61
125                       549829   7.00
158                       463741   5.91
30                        424469   5.41
49                        360291   4.59
35                        327934   4.18
119                       291802   3.72
148                       202707   2.58
26                        190217   2.42
72                        165332   2.11
83                        159854   2.04
160                       155150   1.98
115                       140588   1.79
109                        98365   1.25
120                        87700   1.12
5                          79959   1.02
64                         72127   0.92
74                         64255   0.82
20                         56801   0.72
28                         41521   0.53
58                         33882   0.43
140                        32311   0.41
128                        25489   0.32
24                         22747   0.29
105                        19119   0.24
130                        18769   0.24
151                        17850   0.23
11                         17802   0.23
44                         16063   0.20
62                         14327   0.18
123                        12354   0.16
145                        10481   0.13
48                          8595   0.11
156                         6842   0.09
90                          5973   0.08
68                          4983   0.06
136                         4340   0.06
38                          2901   0.04
92                          2840   0.04
159                         2500   0.03
17                          2070   0.03
133                            3   0.00
71                             4   0.00
66                             3   0.00
153                            3   0.00
143                            3   0.00
104                            3   0.00
134                            3   0.00
85                             3   0.00
45                             5   0.00
89                             3   0.00
111                            5   0.00
106                            8   0.00
77                             5   0.00
43                             6   0.00
41                             7   0.00
33                             8   0.00
16                            10   0.00
135                           10   0.00
102                           11   0.00
81                            11   0.00
132                           12   0.00
25                            12   0.00
138                            3   0.00
86                             1   0.00
127                            3   0.00
144                            2   0.00
101                            1   0.00
18                             1   0.00
96                             1   0.00
78                            13   0.00
14                             1   0.00
114                            1   0.00
79                             1   0.00
13                             1   0.00
8                              1   0.00
61                             1   0.00
57                             1   0.00
155                            1   0.00
3                              1   0.00
46                             1   0.00
117                            1   0.00
67                             2   0.00
97                             2   0.00
55                             2   0.00
1                              2   0.00
142                            2   0.00
150                            2   0.00
60                            13   0.00
129                           50   0.00
141                           15   0.00
9                             16   0.00
131                           75   0.00
29                            77   0.00
157                           77   0.00
63                            84   0.00
40                            90   0.00
116                           90   0.00
152                           92   0.00
91                            95   0.00
146                           97   0.00
6                            100   0.00
15                           115   0.00
36                           119   0.00
51                           131   0.00
12                           152   0.00
37                           175   0.00
59                           182   0.00
54                           186   0.00
32                           229   0.00
161                          236   0.00
42                           275   0.00
126                          369   0.00
93                            73   0.00
121                           69   0.00
65                            66   0.00
69                            31   0.00
98                            17   0.00
95                            19   0.00
80                            20   0.00
39                            22   0.00
139                           23   0.00
110                           25   0.00
75                            25   0.00
70                            28   0.00
76                            29   0.00
21                            32   0.00
19                            63   0.00
7                             35   0.00
149                           37   0.00
162                           37   0.00
73                            43   0.00
27                            44   0.00
84                            45   0.00
124                           49   0.00
122                           50   0.00
50                            62   0.00
56                             1   0.00

In [91]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                             HasDetections      cnt    rate
Census_OSUILocaleIdentifier
31                               1606877.0  3170824   50.68
34                                532015.0  1040042   51.15
125                               253204.0   498236   50.82
30                                249447.0   513995   48.53
158                               211376.0   408118   51.79
49                                205293.0   436691   47.01
35                                203579.0   377071   53.99
119                               171996.0   337988   50.89
26                                111208.0   252863   43.98
148                               107373.0   206854   51.91
160                               101591.0   201983   50.30
72                                 93121.0   191930   48.52
83                                 82054.0   170681   48.07
109                                67070.0   142479   47.07
115                                63378.0   132758   47.74
120                                53483.0   108817   49.15
64                                 45873.0    84426   54.34
5                                  40101.0    81845   49.00
74                                 36626.0    84458   43.37
20                                 33011.0    72672   45.42
28                                 23996.0    50797   47.24
58                                 21771.0    41994   51.84
140                                20472.0    48933   41.84
24                                 14510.0    35558   40.81
128                                14442.0    32294   44.72
130                                11855.0    22721   52.18
105                                11494.0    29567   38.87
11                                 11167.0    18618   59.98
151                                 8724.0    14903   58.54
62                                  7923.0    16130   49.12
44                                  7282.0    19963   36.48
123                                 5769.0    12860   44.86
145                                 5642.0    10779   52.34
48                                  5494.0    11113   49.44
90                                  3747.0     7206   52.00
156                                 3730.0     7726   48.28
68                                  2586.0     4615   56.03
136                                 2337.0     4629   50.49
159                                 1651.0     3917   42.15
92                                  1487.0     3450   43.10
38                                  1319.0     3340   39.49
17                                  1053.0     2171   48.50
126                                  136.0      216   62.96
42                                   124.0      286   43.36
161                                  106.0      164   64.63
32                                    91.0      207   43.96
54                                    88.0      170   51.76
59                                    78.0      161   48.45
15                                    74.0      187   39.57
12                                    59.0       98   60.20
36                                    49.0       83   59.04
37                                    49.0      106   46.23
157                                   46.0       87   52.87
51                                    44.0       83   53.01
121                                   41.0       64   64.06
29                                    39.0       68   57.35
40                                    37.0       67   55.22
63                                    35.0       53   66.04
93                                    33.0       60   55.00
116                                   33.0       64   51.56
6                                     32.0       58   55.17
131                                   31.0       52   59.62
152                                   30.0       48   62.50
91                                    29.0       51   56.86
146                                   29.0       68   42.65
7                                     23.0       46   50.00
129                                   22.0       42   52.38
162                                   22.0       42   52.38
50                                    22.0       44   50.00
73                                    20.0       48   41.67
70                                    18.0       49   36.73
76                                    17.0       36   47.22
122                                   17.0       35   48.57
124                                   16.0       28   57.14
80                                    16.0       28   57.14
84                                    15.0       42   35.71
27                                    15.0       36   41.67
65                                    15.0       33   45.45
149                                   15.0       18   83.33
110                                   14.0       38   36.84
95                                    14.0       22   63.64
75                                    14.0       28   50.00
21                                    13.0       27   48.15
132                                   13.0       27   48.15
19                                    12.0       29   41.38
39                                    12.0       25   48.00
135                                    9.0       11   81.82
98                                     9.0       15   60.00
9                                      7.0        9   77.78
139                                    7.0       14   50.00
141                                    6.0       20   30.00
69                                     5.0       14   35.71
45                                     4.0        8   50.00
33                                     3.0        7   42.86
153                                    3.0        4   75.00
16                                     3.0        6   50.00
150                                    2.0        3   66.67
138                                    2.0        4   50.00
143                                    2.0        4   50.00
78                                     2.0        4   50.00
111                                    2.0        8   25.00
3                                      2.0        2  100.00
2                                      2.0        5   40.00
106                                    2.0        3   66.67
10                                     2.0        2  100.00
102                                    2.0        6   33.33
82                                     2.0        2  100.00
77                                     2.0        4   50.00
66                                     2.0        3   66.67
25                                     2.0        5   40.00
60                                     2.0       13   15.38
18                                     1.0        1  100.00
61                                     1.0        1  100.00
113                                    1.0        1  100.00
56                                     1.0        1  100.00
144                                    1.0        1  100.00
55                                     1.0        2   50.00
147                                    1.0        1  100.00
41                                     1.0        4   25.00
155                                    1.0        1  100.00
46                                     1.0        3   33.33
134                                    1.0        2   50.00
133                                    1.0        2   50.00
43                                     1.0        1  100.00
85                                     1.0        2   50.00
86                                     1.0        2   50.00
87                                     1.0        3   33.33
13                                     1.0        3   33.33
96                                     1.0        2   50.00
99                                     1.0        3   33.33
107                                    1.0        2   50.00
8                                      1.0        4   25.00
14                                     0.0        1    0.00
22                                     0.0        1    0.00
112                                    0.0        2    0.00
67                                     0.0        1    0.00
52                                     0.0        1    0.00
57                                     0.0        1    0.00
142                                    0.0        4    0.00
71                                     0.0        3    0.00
81                                     0.0        4    0.00
127                                    0.0        1    0.00
89                                     0.0        3    0.00
104                                    0.0        1    0.00
117                                    0.0        1    0.00
108                                    0.0        1    0.00
1                                      0.0        1    0.00

### Census_OSWUAutoUpdateOptionsName

In [92]:
col = 'Census_OSWUAutoUpdateOptionsName'

In [93]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

                                       Census_OSWUAutoUpdateOptionsName   rate
FullAuto                                                        3954497  44.33
UNKNOWN                                                         2519925  28.25
Notify                                                          2034254  22.80
AutoInstallAndRebootAtMaintenanceTime                            371475   4.16
Off                                                               26961   0.30
DownloadNotify                                                    14371   0.16

In [94]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

                                       Census_OSWUAutoUpdateOptionsName   rate
FullAuto                                                        4113612  52.38
UNKNOWN                                                         2299918  29.29
Notify                                                          1194458  15.21
AutoInstallAndRebootAtMaintenanceTime                            213891   2.72
Off                                                               20388   0.26
DownloadNotify                                                    10986   0.14

In [95]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                                       HasDetections      cnt   rate
Census_OSWUAutoUpdateOptionsName
FullAuto                                   2040783.0  3954497  51.61
UNKNOWN                                    1252056.0  2519925  49.69
Notify                                      967026.0  2034254  47.54
AutoInstallAndRebootAtMaintenanceTime       181112.0   371475  48.75
Off                                          12891.0    26961  47.81
DownloadNotify                                5024.0    14371  34.96

### Census_IsPortableOperatingSystem

In [96]:
col = 'Census_IsPortableOperatingSystem'

In [97]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

   Census_IsPortableOperatingSystem   rate
0                           8916619  99.95
1                              4864   0.05

In [98]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

   Census_IsPortableOperatingSystem   rate
0                           7848659  99.94
1                              4594   0.06

In [99]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                                  HasDetections      cnt   rate
Census_IsPortableOperatingSystem
0                                     4456201.0  8916619  49.98
1                                        2691.0     4864  55.32

### Census_GenuineStateName

In [100]:
col = 'Census_GenuineStateName'

In [101]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

                 Census_GenuineStateName   rate
IS_GENUINE                       7877597  88.30
INVALID_LICENSE                   801692   8.99
OFFLINE                           228366   2.56
UNKNOWN                            13826   0.15
TAMPERED                               2   0.00

In [102]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

                 Census_GenuineStateName   rate
IS_GENUINE                       6729893  85.70
INVALID_LICENSE                   875327  11.15
OFFLINE                           232931   2.97
UNKNOWN                            15100   0.19
NaN                                    1   0.00
TAMPERED                               1   0.00

In [103]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                         HasDetections      cnt   rate
Census_GenuineStateName
IS_GENUINE                   3935480.0  7877597  49.96
INVALID_LICENSE               395483.0   801692  49.33
OFFLINE                       123740.0   228366  54.18
UNKNOWN                         4188.0    13826  30.29
TAMPERED                           1.0        2  50.00

### Census_ActivationChannel

In [104]:
col = 'Census_ActivationChannel'

In [105]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

                Census_ActivationChannel   rate
Retail                           4727589  52.99
OEM:DM                           3413350  38.26
Volume:GVLK                       450954   5.05
OEM:NONSLP                        317980   3.56
Volume:MAK                          8028   0.09
Retail:TB:Eval                      3582   0.04

In [106]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

                Census_ActivationChannel   rate
Retail                           4051234  51.59
OEM:DM                           2815395  35.85
Volume:GVLK                       710466   9.05
OEM:NONSLP                        261287   3.33
Volume:MAK                         12512   0.16
Retail:TB:Eval                      2359   0.03

In [107]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                          HasDetections      cnt   rate
Census_ActivationChannel
Retail                        2325719.0  4727589  49.19
OEM:DM                        1695147.0  3413350  49.66
Volume:GVLK                    268182.0   450954  59.47
OEM:NONSLP                     165240.0   317980  51.97
Volume:MAK                       3622.0     8028  45.12
Retail:TB:Eval                    982.0     3582  27.41

### Census_IsFlightingInternal

In [108]:
col = 'Census_IsFlightingInternal'

In [109]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

      Census_IsFlightingInternal   rate
NaN                      7408759  83.04
 0.0                     1512703  16.96
 1.0                          21   0.00

In [110]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

      Census_IsFlightingInternal   rate
NaN                      6673962  84.98
 0.0                     1179278  15.02
 1.0                          13   0.00

In [111]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                            HasDetections      cnt   rate
Census_IsFlightingInternal
0.0                              737583.0  1512703  48.76
1.0                                  13.0       21  61.90

### Census_IsFlightsDisabled

In [112]:
col = 'Census_IsFlightsDisabled'

In [113]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

      Census_IsFlightsDisabled  rate
 0.0                   8760872  98.2
NaN                     160523   1.8
 1.0                        88   0.0

In [114]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

      Census_IsFlightsDisabled  rate
 0.0                   7727414  98.4
NaN                     125801   1.6
 1.0                        38   0.0

In [115]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                          HasDetections      cnt   rate
Census_IsFlightsDisabled
0.0                           4377413.0  8760872  49.97
1.0                                 5.0       88   5.68

### Census_FlightRing

In [116]:
col = 'Census_FlightRing'

In [117]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

          Census_FlightRing   rate
Retail              8355679  93.66
NOT_SET              287803   3.23
Unknown              243438   2.73
WIS                   10648   0.12
WIF                   10322   0.12
RP                     9860   0.11
Disabled               3722   0.04
OSG                       7   0.00
Canary                    3   0.00
Invalid                   1   0.00

In [118]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

          Census_FlightRing   rate
Retail              7340769  93.47
NOT_SET              270817   3.45
Unknown              201243   2.56
RP                    16909   0.22
WIF                   10113   0.13
WIS                   10015   0.13
Disabled               3379   0.04
OSG                       4   0.00
Canary                    2   0.00
Invalid                   1   0.00
CBCanary                  1   0.00

In [119]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                   HasDetections      cnt    rate
Census_FlightRing
Retail                 4185842.0  8355679   50.10
NOT_SET                 143854.0   287803   49.98
Unknown                 113261.0   243438   46.53
RP                        4876.0     9860   49.45
WIF                       4635.0    10322   44.90
WIS                       4547.0    10648   42.70
Disabled                  1875.0     3722   50.38
Canary                       1.0        3   33.33
Invalid                      1.0        1  100.00
OSG                          0.0        7    0.00

### Census_ThresholdOptIn

In [120]:
col = 'Census_ThresholdOptIn'

In [121]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

      Census_ThresholdOptIn   rate
NaN                 5667325  63.52
 0.0                3253342  36.47
 1.0                    816   0.01

In [122]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

      Census_ThresholdOptIn   rate
NaN                 5529515  70.41
 0.0                2323086  29.58
 1.0                    652   0.01

In [123]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                       HasDetections      cnt   rate
Census_ThresholdOptIn
0.0                        1600755.0  3253342  49.20
1.0                            382.0      816  46.81

### Census_FirmwareManufacturerIdentifier

In [124]:
col = 'Census_FirmwareManufacturerIdentifier'

In [125]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

         Census_FirmwareManufacturerIdentifier   rate
 142.0                                 2699078  30.25
 628.0                                 1229140  13.78
 554.0                                 1175137  13.17
 355.0                                  941793  10.56
 556.0                                  800536   8.97
 500.0                                  385327   4.32
 93.0                                   192481   2.16
NaN                                     183257   2.05
 807.0                                  157172   1.76
 513.0                                  142388   1.60
 127.0                                  123667   1.39
 897.0                                  110223   1.24
 486.0                                  107065   1.20
 512.0                                   91277   1.02
 677.0                                   84042   0.94
 168.0                                   79855   0.90
 803.0                                   59145   0.66
 644.0                                   49496   0.55
 559.0                                   46069   0.52
 444.0                                   29212   0.33
 152.0                                   24463   0.27
 809.0                                   23420   0.26
 134.0                                   19696   0.22
 781.0                                   14739   0.17
 440.0                                   13224   0.15
 691.0                                   11662   0.13
 789.0                                   10138   0.11
 105.0                                    9402   0.11
 798.0                                    9363   0.10
 633.0                                    5920   0.07
 442.0                                    6324   0.07
 299.0                                    5135   0.06
 491.0                                    4994   0.06
 465.0                                    4715   0.05
 1075.0                                   4598   0.05
 361.0                                    4391   0.05
 106.0                                    4266   0.05
 360.0                                    3978   0.04
 845.0                                    3114   0.03
 446.0                                    2459   0.03
 560.0                                    2316   0.03
 839.0                                    1433   0.02
 831.0                                    1475   0.02
 820.0                                    1528   0.02
 827.0                                    1801   0.02
 639.0                                    1910   0.02
 819.0                                    2056   0.02
 1030.0                                   2082   0.02
 869.0                                    2123   0.02
 892.0                                     586   0.01
 991.0                                     449   0.01
 537.0                                     452   0.01
 140.0                                     461   0.01
 107.0                                     485   0.01
 876.0                                     518   0.01
 85.0                                      527   0.01
 1040.0                                    551   0.01
 488.0                                     569   0.01
 357.0                                     585   0.01
 1014.0                                    745   0.01
 522.0                                     624   0.01
 279.0                                     786   0.01
 369.0                                    1248   0.01
 150.0                                     657   0.01
 196.0                                     890   0.01
 1080.0                                    842   0.01
 311.0                                    1225   0.01
 109.0                                     741   0.01
 888.0                                     684   0.01
 520.0                                     673   0.01
 910.0                                       2   0.00
 467.0                                       2   0.00
 481.0                                       2   0.00
 248.0                                       2   0.00
 779.0                                       2   0.00
...                                        ...    ...
 607.0                                      14   0.00
 1044.0                                     14   0.00
 544.0                                      14   0.00
 709.0                                      14   0.00
 90.0                                       14   0.00
 117.0                                      13   0.00
 590.0                                      15   0.00
 825.0                                      13   0.00
 419.0                                      13   0.00
 492.0                                      13   0.00
 954.0                                      13   0.00
 721.0                                      13   0.00
 1024.0                                     13   0.00
 194.0                                      12   0.00
 325.0                                      14   0.00
 975.0                                      15   0.00
 283.0                                      12   0.00
 130.0                                      17   0.00
 542.0                                      18   0.00
 231.0                                      18   0.00
 967.0                                      18   0.00
 568.0                                      17   0.00
 836.0                                      17   0.00
 319.0                                      17   0.00
 153.0                                      17   0.00
 678.0                                      16   0.00
 636.0                                      15   0.00
 563.0                                      16   0.00
 800.0                                      16   0.00
 330.0                                      16   0.00
 981.0                                      16   0.00
 581.0                                      15   0.00
 203.0                                      15   0.00
 215.0                                      15   0.00
 291.0                                      12   0.00
 1023.0                                     12   0.00
 13.0                                        8   0.00
 841.0                                       9   0.00
 66.0                                       10   0.00
 921.0                                      10   0.00
 89.0                                       10   0.00
 685.0                                      10   0.00
 549.0                                       9   0.00
 925.0                                       9   0.00
 719.0                                       9   0.00
 555.0                                       9   0.00
 703.0                                      10   0.00
 281.0                                       9   0.00
 933.0                                       9   0.00
 112.0                                       9   0.00
 760.0                                       9   0.00
 268.0                                       9   0.00
 1067.0                                      9   0.00
 960.0                                       8   0.00
 366.0                                      10   0.00
 638.0                                      10   0.00
 736.0                                      12   0.00
 285.0                                      11   0.00
 1058.0                                     12   0.00
 700.0                                      12   0.00
 94.0                                       12   0.00
 765.0                                      12   0.00
 716.0                                      11   0.00
 441.0                                      11   0.00
 539.0                                      11   0.00
 618.0                                      11   0.00
 427.0                                      10   0.00
 761.0                                      11   0.00
 534.0                                      10   0.00
 680.0                                      10   0.00
 436.0                                      10   0.00
 854.0                                      10   0.00
 1065.0                                     10   0.00
 941.0                                      10   0.00
 2.0                                         1   0.00

[713 rows x 2 columns]

In [126]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

         Census_FirmwareManufacturerIdentifier   rate
 142.0                                 2442080  31.10
 628.0                                 1071331  13.64
 554.0                                  982632  12.51
 355.0                                  847687  10.79
 556.0                                  650852   8.29
 500.0                                  345645   4.40
NaN                                     198634   2.53
 93.0                                   171689   2.19
 807.0                                  128554   1.64
 513.0                                  113513   1.45
 127.0                                  105729   1.35
 486.0                                  103190   1.31
 897.0                                   89188   1.14
 512.0                                   75183   0.96
 168.0                                   74913   0.95
 677.0                                   74195   0.94
 803.0                                   50964   0.65
 559.0                                   42706   0.54
 644.0                                   40676   0.52
 152.0                                   30044   0.38
 444.0                                   25188   0.32
 809.0                                   20188   0.26
 134.0                                   17189   0.22
 781.0                                   11967   0.15
 440.0                                   11518   0.15
 789.0                                   10308   0.13
 691.0                                    8368   0.11
 105.0                                    8028   0.10
 633.0                                    7977   0.10
 798.0                                    7799   0.10
 491.0                                    6851   0.09
 442.0                                    4664   0.06
 465.0                                    4068   0.05
 1075.0                                   3791   0.05
 106.0                                    3708   0.05
 360.0                                    3554   0.05
 299.0                                    4272   0.05
 361.0                                    3353   0.04
 845.0                                    2791   0.04
 869.0                                    2008   0.03
 1030.0                                   1988   0.03
 1014.0                                   2271   0.03
 560.0                                    2026   0.03
 446.0                                    2095   0.03
 892.0                                    1178   0.02
 831.0                                    1201   0.02
 839.0                                    1231   0.02
 109.0                                    1213   0.02
 639.0                                    1550   0.02
 819.0                                    1543   0.02
 827.0                                    1717   0.02
 820.0                                    1757   0.02
 150.0                                     550   0.01
 107.0                                     395   0.01
 991.0                                     397   0.01
 357.0                                     411   0.01
 422.0                                     420   0.01
 1040.0                                    424   0.01
 85.0                                      430   0.01
 279.0                                     504   0.01
 488.0                                     507   0.01
 196.0                                     747   0.01
 522.0                                     563   0.01
 888.0                                     736   0.01
 140.0                                     884   0.01
 1080.0                                    572   0.01
 671.0                                     796   0.01
 369.0                                     810   0.01
 311.0                                     647   0.01
 520.0                                     603   0.01
 876.0                                     588   0.01
 82.0                                        2   0.00
 504.0                                       2   0.00
 741.0                                       2   0.00
 71.0                                        2   0.00
...                                        ...    ...
 285.0                                      11   0.00
 544.0                                      11   0.00
 1058.0                                     11   0.00
 215.0                                      11   0.00
 130.0                                      11   0.00
 700.0                                      11   0.00
 716.0                                      11   0.00
 800.0                                      11   0.00
 657.0                                      10   0.00
 417.0                                      10   0.00
 555.0                                      10   0.00
 596.0                                      10   0.00
 90.0                                       10   0.00
 753.0                                      10   0.00
 836.0                                      12   0.00
 542.0                                      12   0.00
 194.0                                      12   0.00
 155.0                                      13   0.00
 289.0                                      14   0.00
 277.0                                      14   0.00
 257.0                                      14   0.00
 325.0                                      14   0.00
 1054.0                                     14   0.00
 283.0                                      14   0.00
 316.0                                      13   0.00
 290.0                                      13   0.00
 427.0                                      12   0.00
 291.0                                      13   0.00
 346.0                                      13   0.00
 703.0                                      13   0.00
 707.0                                      13   0.00
 391.0                                      13   0.00
 181.0                                      12   0.00
 441.0                                      12   0.00
 34.0                                       10   0.00
 592.0                                      10   0.00
 203.0                                      10   0.00
 197.0                                       8   0.00
 94.0                                        8   0.00
 206.0                                       8   0.00
 945.0                                       8   0.00
 139.0                                       8   0.00
 563.0                                       8   0.00
 534.0                                       8   0.00
 117.0                                       8   0.00
 946.0                                       8   0.00
 74.0                                        8   0.00
 975.0                                       8   0.00
 719.0                                       8   0.00
 765.0                                       8   0.00
 610.0                                       8   0.00
 761.0                                       8   0.00
 788.0                                       8   0.00
 624.0                                       8   0.00
 227.0                                       8   0.00
 249.0                                       8   0.00
 941.0                                      10   0.00
 313.0                                       9   0.00
 692.0                                      10   0.00
 568.0                                      10   0.00
 958.0                                      10   0.00
 612.0                                       9   0.00
 852.0                                       9   0.00
 549.0                                       9   0.00
 967.0                                       9   0.00
 262.0                                       9   0.00
 419.0                                       8   0.00
 685.0                                       9   0.00
 1061.0                                      9   0.00
 962.0                                       9   0.00
 1023.0                                      9   0.00
 760.0                                       9   0.00
 398.0                                       9   0.00
 736.0                                       9   0.00
 3.0                                         1   0.00

[723 rows x 2 columns]

In [127]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                                       HasDetections      cnt   rate
Census_FirmwareManufacturerIdentifier
142.0                                      1400255.0  2699078  51.88
628.0                                       616527.0  1229140  50.16
554.0                                       599526.0  1175137  51.02
355.0                                       482124.0   941793  51.19
556.0                                       404023.0   800536  50.47
500.0                                       180328.0   385327  46.80
93.0                                        101111.0   192481  52.53
807.0                                        74714.0   157172  47.54
513.0                                        57228.0   142388  40.19
127.0                                        55494.0   123667  44.87
486.0                                        54404.0   107065  50.81
897.0                                        51225.0   110223  46.47
168.0                                        41258.0    79855  51.67
677.0                                        40765.0    84042  48.51
512.0                                        40428.0    91277  44.29
644.0                                        24395.0    49496  49.29
803.0                                        20907.0    59145  35.35
559.0                                        20605.0    46069  44.73
444.0                                        13319.0    29212  45.59
134.0                                        10545.0    19696  53.54
809.0                                        10389.0    23420  44.36
152.0                                         8579.0    24463  35.07
781.0                                         6441.0    14739  43.70
440.0                                         6185.0    13224  46.77
691.0                                         5259.0    11662  45.10
105.0                                         4980.0     9402  52.97
798.0                                         3753.0     9363  40.08
633.0                                         3197.0     5920  54.00
491.0                                         2805.0     4994  56.17
442.0                                         2728.0     6324  43.14
299.0                                         2410.0     5135  46.93
789.0                                         2386.0    10138  23.54
361.0                                         2372.0     4391  54.02
465.0                                         2219.0     4715  47.06
360.0                                         1988.0     3978  49.97
106.0                                         1803.0     4266  42.26
1075.0                                        1727.0     4598  37.56
845.0                                         1261.0     3114  40.49
446.0                                         1143.0     2459  46.48
819.0                                         1034.0     2056  50.29
827.0                                         1031.0     1801  57.25
639.0                                         1029.0     1910  53.87
560.0                                          915.0     2316  39.51
831.0                                          825.0     1475  55.93
1030.0                                         825.0     2082  39.63
839.0                                          731.0     1433  51.01
369.0                                          716.0     1248  57.37
820.0                                          707.0     1528  46.27
311.0                                          671.0     1225  54.78
1014.0                                         440.0      745  59.06
109.0                                          393.0      741  53.04
279.0                                          393.0      786  50.00
869.0                                          390.0     2123  18.37
1080.0                                         377.0      842  44.77
892.0                                          348.0      586  59.39
520.0                                          315.0      673  46.81
522.0                                          313.0      624  50.16
150.0                                          306.0      657  46.58
888.0                                          290.0      684  42.40
350.0                                          251.0      443  56.66
301.0                                          237.0      375  63.20
85.0                                           233.0      527  44.21
140.0                                          223.0      461  48.37
108.0                                          215.0      375  57.33
876.0                                          211.0      518  40.73
359.0                                          181.0      384  47.14
353.0                                          178.0      362  49.17
537.0                                          174.0      452  38.50
488.0                                          170.0      569  29.88
107.0                                          169.0      485  34.85
545.0                                          158.0      316  50.00
671.0                                          153.0      440  34.77
310.0                                          152.0      419  36.28
833.0                                          152.0      315  48.25
196.0                                          151.0      890  16.97
...                                              ...      ...    ...
450.0                                            0.0        1   0.00
835.0                                            0.0        3   0.00
737.0                                            0.0        1   0.00
752.0                                            0.0        3   0.00
490.0                                            0.0        1   0.00
763.0                                            0.0        4   0.00
479.0                                            0.0        3   0.00
474.0                                            0.0        2   0.00
767.0                                            0.0        1   0.00
514.0                                            0.0        1   0.00
772.0                                            0.0        2   0.00
745.0                                            0.0        1   0.00
469.0                                            0.0        1   0.00
779.0                                            0.0        2   0.00
780.0                                            0.0        1   0.00
744.0                                            0.0        2   0.00
783.0                                            0.0        1   0.00
462.0                                            0.0        1   0.00
459.0                                            0.0        1   0.00
788.0                                            0.0        5   0.00
457.0                                            0.0        1   0.00
456.0                                            0.0        1   0.00
742.0                                            0.0        1   0.00
801.0                                            0.0        4   0.00
724.0                                            0.0        1   0.00
532.0                                            0.0        2   0.00
929.0                                            0.0        1   0.00
885.0                                            0.0        1   0.00
272.0                                            0.0        1   0.00
707.0                                            0.0       20   0.00
266.0                                            0.0        2   0.00
265.0                                            0.0        1   0.00
895.0                                            0.0        1   0.00
262.0                                            0.0        1   0.00
260.0                                            0.0        1   0.00
255.0                                            0.0        1   0.00
253.0                                            0.0        1   0.00
250.0                                            0.0        2   0.00
248.0                                            0.0        2   0.00
906.0                                            0.0        1   0.00
907.0                                            0.0        1   0.00
910.0                                            0.0        2   0.00
914.0                                            0.0        3   0.00
915.0                                            0.0        5   0.00
505.0                                            0.0        2   0.00
244.0                                            0.0        1   0.00
241.0                                            0.0        1   0.00
236.0                                            0.0        3   0.00
927.0                                            0.0       21   0.00
274.0                                            0.0        1   0.00
278.0                                            0.0        1   0.00
837.0                                            0.0        1   0.00
565.0                                            0.0        1   0.00
341.0                                            0.0        1   0.00
334.0                                            0.0        3   0.00
847.0                                            0.0        1   0.00
333.0                                            0.0        4   0.00
328.0                                            0.0        1   0.00
553.0                                            0.0        4   0.00
323.0                                            0.0        1   0.00
318.0                                            0.0        1   0.00
716.0                                            0.0       11   0.00
856.0                                            0.0        1   0.00
857.0                                            0.0        1   0.00
860.0                                            0.0        1   0.00
864.0                                            0.0        1   0.00
656.0                                            0.0        1   0.00
304.0                                            0.0        1   0.00
300.0                                            0.0        2   0.00
296.0                                            0.0        3   0.00
872.0                                            0.0        2   0.00
294.0                                            0.0        2   0.00
714.0                                            0.0        3   0.00
286.0                                            0.0        2   0.00
660.0                                            0.0        1   0.00

[712 rows x 3 columns]

### Census_FirmwareVersionIdentifier

In [128]:
col = 'Census_FirmwareVersionIdentifier'

In [129]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

          Census_FirmwareVersionIdentifier  rate
NaN                                 160133  1.79
 33105.0                             89611  1.00
 33111.0                             61583  0.69
 33054.0                             56626  0.63
 33108.0                             55040  0.62
 11778.0                             53785  0.60
 63175.0                             52504  0.59
 33115.0                             50972  0.57
 63155.0                             49074  0.55
 33060.0                             48587  0.54
 19970.0                             46679  0.52
 33070.0                             46168  0.52
 63122.0                             45316  0.51
 19951.0                             44506  0.50
 19948.0                             43279  0.49
 19973.0                             41755  0.47
 33075.0                             41563  0.47
 33142.0                             40841  0.46
 63140.0                             40025  0.45
 33778.0                             39385  0.44
 20106.0                             39167  0.44
 63317.0                             39111  0.44
 63269.0                             39097  0.44
 33043.0                             38640  0.43
 33000.0                             37403  0.42
 19946.0                             36270  0.41
 19956.0                             36348  0.41
 33135.0                             35951  0.40
 19982.0                             35578  0.40
 63417.0                             34561  0.39
 12536.0                             33564  0.38
 63396.0                             33316  0.37
 63041.0                             33075  0.37
 20050.0                             32650  0.37
 63086.0                             32261  0.36
 63069.0                             32285  0.36
 33041.0                             31538  0.35
 33137.0                             31360  0.35
 33133.0                             31059  0.35
 63103.0                             30611  0.34
 20107.0                             30198  0.34
 33066.0                             30061  0.34
 12459.0                             29102  0.33
 33084.0                             29111  0.33
 7271.0                              29211  0.33
 33116.0                             29346  0.33
 33130.0                             29406  0.33
 7145.0                              29829  0.33
 33015.0                             28947  0.32
 7221.0                              28586  0.32
 4357.0                              27719  0.31
 33026.0                             27273  0.31
 20317.0                             27667  0.31
 33264.0                             27440  0.31
 19931.0                             27891  0.31
 33103.0                             27915  0.31
 6899.0                              27935  0.31
 7759.0                              27019  0.30
 33076.0                             26282  0.29
 3828.0                              25826  0.29
 9321.0                              25529  0.29
 34322.0                             25346  0.28
 63370.0                             25155  0.28
 33086.0                             24962  0.28
 33032.0                             24180  0.27
 34558.0                             22857  0.26
 33006.0                             23049  0.26
 33080.0                             22441  0.25
 7314.0                              21865  0.25
 19889.0                             22531  0.25
 13299.0                             21830  0.24
 33094.0                             21810  0.24
 33039.0                             21735  0.24
 20246.0                             21552  0.24
 33139.0                             20171  0.23
...                                    ...   ...
 51614.0                                17  0.00
 56446.0                                17  0.00
 59145.0                                17  0.00
 69395.0                                17  0.00
 51757.0                                17  0.00
 29519.0                                17  0.00
 61729.0                                17  0.00
 29482.0                                17  0.00
 15271.0                                17  0.00
 33241.0                                17  0.00
 30966.0                                17  0.00
 29517.0                                17  0.00
 56147.0                                17  0.00
 66831.0                                17  0.00
 40908.0                                17  0.00
 28888.0                                17  0.00
 41105.0                                17  0.00
 15050.0                                17  0.00
 14084.0                                17  0.00
 13110.0                                17  0.00
 43714.0                                17  0.00
 45144.0                                17  0.00
 31151.0                                17  0.00
 71130.0                                17  0.00
 15302.0                                17  0.00
 43742.0                                17  0.00
 30286.0                                17  0.00
 43713.0                                17  0.00
 56321.0                                17  0.00
 9104.0                                 17  0.00
 44366.0                                17  0.00
 10694.0                                17  0.00
 45424.0                                17  0.00
 2220.0                                 17  0.00
 30541.0                                17  0.00
 19101.0                                17  0.00
 30479.0                                17  0.00
 51593.0                                17  0.00
 52160.0                                17  0.00
 14651.0                                17  0.00
 29423.0                                17  0.00
 51516.0                                17  0.00
 55574.0                                17  0.00
 51571.0                                17  0.00
 51432.0                                17  0.00
 15351.0                                17  0.00
 2304.0                                 17  0.00
 37531.0                                17  0.00
 13961.0                                17  0.00
 18360.0                                17  0.00
 2954.0                                 17  0.00
 5337.0                                 17  0.00
 37480.0                                17  0.00
 56959.0                                17  0.00
 51765.0                                17  0.00
 63226.0                                17  0.00
 30521.0                                17  0.00
 31117.0                                17  0.00
 5326.0                                 17  0.00
 59281.0                                17  0.00
 40793.0                                17  0.00
 70552.0                                17  0.00
 37421.0                                17  0.00
 43973.0                                17  0.00
 2093.0                                 17  0.00
 56378.0                                17  0.00
 58180.0                                17  0.00
 29251.0                                17  0.00
 58964.0                                17  0.00
 30568.0                                17  0.00
 29639.0                                17  0.00
 64134.0                                17  0.00
 19109.0                                17  0.00
 8518.0                                 17  0.00
 3.0                                     1  0.00

[50495 rows x 2 columns]

In [130]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

          Census_FirmwareVersionIdentifier  rate
NaN                                 177624  2.26
 33105.0                             72448  0.92
 33054.0                             52437  0.67
 11778.0                             51806  0.66
 33111.0                             46768  0.60
 33108.0                             43862  0.56
 63175.0                             41789  0.53
 33000.0                             41648  0.53
 19970.0                             40291  0.51
 33060.0                             40257  0.51
 19951.0                             39132  0.50
 33778.0                             39626  0.50
 33115.0                             38756  0.49
 63155.0                             38637  0.49
 33070.0                             37710  0.48
 19948.0                             36244  0.46
 63122.0                             36120  0.46
 19973.0                             35567  0.45
 33075.0                             33991  0.43
 33142.0                             33697  0.43
 63140.0                             33538  0.43
 20106.0                             33299  0.42
 63269.0                             31823  0.41
 19956.0                             31727  0.40
 19946.0                             31571  0.40
 33135.0                             31255  0.40
 63317.0                             30680  0.39
 19982.0                             30076  0.38
 33137.0                             29764  0.38
 33043.0                             29678  0.38
 63417.0                             29586  0.38
 20050.0                             28543  0.36
 33264.0                             27393  0.35
 33066.0                             27678  0.35
 12536.0                             27682  0.35
 33015.0                             26905  0.34
 33133.0                             26843  0.34
 33130.0                             26701  0.34
 63396.0                             26547  0.34
 20107.0                             26320  0.34
 63086.0                             25659  0.33
 33026.0                             25544  0.33
 63041.0                             25071  0.32
 7271.0                              24910  0.32
 63069.0                             25136  0.32
 34322.0                             25417  0.32
 33041.0                             25258  0.32
 20317.0                             24500  0.31
 7145.0                              24418  0.31
 63103.0                             24317  0.31
 3828.0                              24256  0.31
 12459.0                             24230  0.31
 19931.0                             24051  0.31
 4357.0                              23606  0.30
 33116.0                             23172  0.30
 7221.0                              23817  0.30
 6899.0                              23866  0.30
 63370.0                             23021  0.29
 33084.0                             22520  0.29
 33103.0                             22185  0.28
 34558.0                             21778  0.28
 33076.0                             20798  0.26
 13299.0                             20089  0.26
 20246.0                             19418  0.25
 19889.0                             19535  0.25
 33157.0                             19770  0.25
 33086.0                             19819  0.25
 33006.0                             20013  0.25
 33032.0                             19116  0.24
 7314.0                              18562  0.24
 34833.0                             18548  0.24
 35043.0                             18373  0.23
 32998.0                             18101  0.23
 33144.0                             16943  0.22
 33039.0                             17284  0.22
...                                    ...   ...
 43675.0                                16  0.00
 61113.0                                16  0.00
 49138.0                                16  0.00
 19328.0                                16  0.00
 41861.0                                16  0.00
 36174.0                                16  0.00
 28921.0                                16  0.00
 63229.0                                16  0.00
 14816.0                                16  0.00
 46549.0                                16  0.00
 18143.0                                16  0.00
 59549.0                                16  0.00
 45182.0                                16  0.00
 70490.0                                16  0.00
 29144.0                                16  0.00
 25157.0                                16  0.00
 938.0                                  16  0.00
 54377.0                                16  0.00
 64976.0                                16  0.00
 29070.0                                16  0.00
 16192.0                                16  0.00
 55597.0                                16  0.00
 41117.0                                16  0.00
 41099.0                                16  0.00
 45243.0                                16  0.00
 61743.0                                16  0.00
 34029.0                                16  0.00
 44435.0                                16  0.00
 34156.0                                16  0.00
 49223.0                                16  0.00
 41920.0                                16  0.00
 41986.0                                16  0.00
 13165.0                                16  0.00
 37976.0                                16  0.00
 7949.0                                 16  0.00
 48869.0                                16  0.00
 24513.0                                16  0.00
 43698.0                                16  0.00
 30196.0                                16  0.00
 4367.0                                 16  0.00
 15278.0                                16  0.00
 17928.0                                16  0.00
 30103.0                                16  0.00
 2060.0                                 16  0.00
 39360.0                                16  0.00
 30284.0                                16  0.00
 12139.0                                16  0.00
 39282.0                                16  0.00
 41911.0                                16  0.00
 49093.0                                16  0.00
 26665.0                                16  0.00
 11091.0                                16  0.00
 11114.0                                16  0.00
 60361.0                                16  0.00
 70307.0                                16  0.00
 67501.0                                16  0.00
 41771.0                                16  0.00
 19427.0                                16  0.00
 60401.0                                16  0.00
 57186.0                                16  0.00
 49277.0                                16  0.00
 66774.0                                16  0.00
 54935.0                                16  0.00
 15442.0                                16  0.00
 19102.0                                16  0.00
 19388.0                                16  0.00
 67421.0                                16  0.00
 29890.0                                16  0.00
 15441.0                                16  0.00
 1127.0                                 16  0.00
 61070.0                                16  0.00
 56939.0                                16  0.00
 35775.0                                16  0.00
 2807.0                                 16  0.00
 5.0                                     1  0.00

[49812 rows x 2 columns]

In [131]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                                  HasDetections    cnt   rate
Census_FirmwareVersionIdentifier
33105.0                                 45370.0  89611  50.63
33111.0                                 31624.0  61583  51.35
33054.0                                 28930.0  56626  51.09
33108.0                                 28068.0  55040  51.00
11778.0                                 28027.0  53785  52.11
33115.0                                 26119.0  50972  51.24
63175.0                                 25437.0  52504  48.45
33060.0                                 23869.0  48587  49.13
19970.0                                 23713.0  46679  50.80
63155.0                                 23689.0  49074  48.27
33070.0                                 22736.0  46168  49.25
19951.0                                 22450.0  44506  50.44
33778.0                                 21972.0  39385  55.79
19948.0                                 21949.0  43279  50.72
63122.0                                 21870.0  45316  48.26
19973.0                                 21488.0  41755  51.46
33142.0                                 21470.0  40841  52.57
33075.0                                 20781.0  41563  50.00
33043.0                                 20454.0  38640  52.93
20106.0                                 19804.0  39167  50.56
63140.0                                 19364.0  40025  48.38
63269.0                                 19244.0  39097  49.22
33000.0                                 18807.0  37403  50.28
63317.0                                 18519.0  39111  47.35
19946.0                                 18430.0  36270  50.81
19982.0                                 18165.0  35578  51.06
33135.0                                 18062.0  35951  50.24
19956.0                                 17996.0  36348  49.51
63417.0                                 17907.0  34561  51.81
63396.0                                 17065.0  33316  51.22
20050.0                                 16636.0  32650  50.95
33041.0                                 16408.0  31538  52.03
33137.0                                 16025.0  31360  51.10
63041.0                                 15812.0  33075  47.81
63069.0                                 15730.0  32285  48.72
63086.0                                 15705.0  32261  48.68
33133.0                                 15332.0  31059  49.36
20107.0                                 15317.0  30198  50.72
7145.0                                  15255.0  29829  51.14
33264.0                                 15060.0  27440  54.88
33084.0                                 14978.0  29111  51.45
7271.0                                  14746.0  29211  50.48
33130.0                                 14703.0  29406  50.00
33116.0                                 14550.0  29346  49.58
7221.0                                  14498.0  28586  50.72
63103.0                                 14371.0  30611  46.95
34322.0                                 14238.0  25346  56.17
33015.0                                 14196.0  28947  49.04
4357.0                                  14186.0  27719  51.18
7759.0                                  14154.0  27019  52.39
33066.0                                 14113.0  30061  46.95
33103.0                                 13776.0  27915  49.35
33026.0                                 13754.0  27273  50.43
20317.0                                 13748.0  27667  49.69
19931.0                                 13703.0  27891  49.13
6899.0                                  13458.0  27935  48.18
9321.0                                  13400.0  25529  52.49
33076.0                                 13039.0  26282  49.61
34558.0                                 12624.0  22857  55.23
63370.0                                 12603.0  25155  50.10
33086.0                                 12540.0  24962  50.24
3828.0                                  12536.0  25826  48.54
33006.0                                 11960.0  23049  51.89
33032.0                                 11905.0  24180  49.23
12536.0                                 11556.0  33564  34.43
33080.0                                 11409.0  22441  50.84
19889.0                                 10970.0  22531  48.69
34833.0                                 10821.0  19053  56.79
33094.0                                 10820.0  21810  49.61
33039.0                                 10709.0  21735  49.27
35043.0                                 10696.0  19036  56.19
12459.0                                 10610.0  29102  36.46
7314.0                                  10600.0  21865  48.48
20246.0                                 10582.0  21552  49.10
12300.0                                 10490.0  19630  53.44
...                                         ...    ...    ...
22842.0                                     0.0      2   0.00
60929.0                                     0.0      2   0.00
39143.0                                     0.0      5   0.00
22839.0                                     0.0      1   0.00
60912.0                                     0.0      1   0.00
22838.0                                     0.0      2   0.00
39146.0                                     0.0      1   0.00
60918.0                                     0.0      2   0.00
22831.0                                     0.0      4   0.00
60926.0                                     0.0      2   0.00
22874.0                                     0.0      1   0.00
39128.0                                     0.0      1   0.00
22882.0                                     0.0      1   0.00
39124.0                                     0.0      1   0.00
60859.0                                     0.0      2   0.00
39098.0                                     0.0      1   0.00
60862.0                                     0.0     16   0.00
39102.0                                     0.0      1   0.00
39103.0                                     0.0      2   0.00
60865.0                                     0.0      1   0.00
39104.0                                     0.0      4   0.00
22905.0                                     0.0      1   0.00
39105.0                                     0.0      1   0.00
39106.0                                     0.0      3   0.00
60873.0                                     0.0      1   0.00
22900.0                                     0.0      1   0.00
39111.0                                     0.0      2   0.00
60877.0                                     0.0      1   0.00
60882.0                                     0.0      1   0.00
39116.0                                     0.0      2   0.00
39121.0                                     0.0      1   0.00
60927.0                                     0.0      1   0.00
60931.0                                     0.0      2   0.00
61012.0                                     0.0      1   0.00
22761.0                                     0.0      1   0.00
39190.0                                     0.0      1   0.00
60974.0                                     0.0      2   0.00
39195.0                                     0.0      2   0.00
22783.0                                     0.0      1   0.00
22775.0                                     0.0      1   0.00
52148.0                                     0.0      2   0.00
22770.0                                     0.0      1   0.00
22765.0                                     0.0      1   0.00
39210.0                                     0.0      1   0.00
22830.0                                     0.0      1   0.00
22749.0                                     0.0      1   0.00
60989.0                                     0.0      1   0.00
22747.0                                     0.0      4   0.00
60992.0                                     0.0      1   0.00
60996.0                                     0.0     10   0.00
60997.0                                     0.0      3   0.00
60998.0                                     0.0      1   0.00
60999.0                                     0.0      1   0.00
22800.0                                     0.0      1   0.00
22801.0                                     0.0      1   0.00
60968.0                                     0.0      1   0.00
60967.0                                     0.0      1   0.00
60939.0                                     0.0      1   0.00
60940.0                                     0.0      1   0.00
60942.0                                     0.0      1   0.00
39153.0                                     0.0      2   0.00
22821.0                                     0.0      3   0.00
60947.0                                     0.0      1   0.00
22819.0                                     0.0      1   0.00
52159.0                                     0.0      1   0.00
39172.0                                     0.0      1   0.00
39181.0                                     0.0      1   0.00
39183.0                                     0.0      6   0.00
22808.0                                     0.0      1   0.00
60956.0                                     0.0      1   0.00
60957.0                                     0.0      2   0.00
39185.0                                     0.0      1   0.00
22802.0                                     0.0      1   0.00
60964.0                                     0.0      1   0.00
3.0                                         0.0      1   0.00

[50494 rows x 3 columns]

### Census_IsSecureBootEnabled

In [132]:
col = 'Census_IsSecureBootEnabled'

In [133]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

   Census_IsSecureBootEnabled  rate
0                     4585438  51.4
1                     4336045  48.6

In [134]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

   Census_IsSecureBootEnabled   rate
0                     4308612  54.86
1                     3544641  45.14

In [135]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                            HasDetections      cnt   rate
Census_IsSecureBootEnabled
0                               2295583.0  4585438  50.06
1                               2163309.0  4336045  49.89

### Census_IsWIMBootEnabled

In [136]:
col = 'Census_IsWIMBootEnabled'

In [137]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

      Census_IsWIMBootEnabled   rate
NaN                   5659703  63.44
 0.0                  3261779  36.56
 1.0                        1   0.00

In [138]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

      Census_IsWIMBootEnabled   rate
NaN                   5522707  70.32
 0.0                  2330545  29.68
 1.0                        1   0.00

In [139]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                         HasDetections      cnt   rate
Census_IsWIMBootEnabled
0.0                          1604572.0  3261779  49.19
1.0                                0.0        1   0.00

### Census_IsVirtualDevice

In [140]:
col = 'Census_IsVirtualDevice'

In [141]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

      Census_IsVirtualDevice   rate
 0.0                 8842840  99.12
 1.0                   62690   0.70
NaN                    15953   0.18

In [142]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

      Census_IsVirtualDevice   rate
 0.0                 7771328  98.96
 1.0                   64634   0.82
NaN                    17291   0.22

In [143]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                        HasDetections      cnt   rate
Census_IsVirtualDevice
0.0                         4438599.0  8842840  50.19
1.0                           12172.0    62690  19.42

### Census_IsTouchEnabled

In [144]:
col = 'Census_IsTouchEnabled'

In [145]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

   Census_IsTouchEnabled   rate
0                7801452  87.45
1                1120031  12.55

In [146]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

   Census_IsTouchEnabled   rate
0                6924286  88.17
1                 928967  11.83

In [147]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                       HasDetections      cnt   rate
Census_IsTouchEnabled
0                          3958835.0  7801452  50.74
1                           500057.0  1120031  44.65

### Census_IsPenCapable

In [148]:
col = 'Census_IsPenCapable'

In [149]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

   Census_IsPenCapable   rate
0              8581834  96.19
1               339649   3.81

In [150]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

   Census_IsPenCapable   rate
0              7555266  96.21
1               297987   3.79

In [151]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                     HasDetections      cnt   rate
Census_IsPenCapable
0                        4303801.0  8581834  50.15
1                         155091.0   339649  45.66

### Census_IsAlwaysOnAlwaysConnectedCapable

In [152]:
col = 'Census_IsAlwaysOnAlwaysConnectedCapable'

In [153]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

      Census_IsAlwaysOnAlwaysConnectedCapable  rate
 0.0                                  8341972  93.5
 1.0                                   508168   5.7
NaN                                     71343   0.8

In [154]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

      Census_IsAlwaysOnAlwaysConnectedCapable   rate
 0.0                                  7340131  93.47
 1.0                                   422970   5.39
NaN                                     90152   1.15

In [155]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                                         HasDetections      cnt   rate
Census_IsAlwaysOnAlwaysConnectedCapable
0.0                                          4232858.0  8341972  50.74
1.0                                           189287.0   508168  37.25

### Wdft_IsGamer

In [156]:
col = 'Wdft_IsGamer'

In [157]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

      Wdft_IsGamer   rate
 0.0       6174143  69.21
 1.0       2443889  27.39
NaN         303451   3.40

In [158]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

      Wdft_IsGamer   rate
 0.0       5302612  67.52
 1.0       2247784  28.62
NaN         302857   3.86

In [159]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

              HasDetections      cnt   rate
Wdft_IsGamer
0.0               2976639.0  6174143  48.21
1.0               1324330.0  2443889  54.19

### Wdft_RegionIdentifier

In [160]:
col = 'Wdft_RegionIdentifier'

In [161]:
print("[train]")
temp = train[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * train[col].value_counts(dropna=False) / train.shape[0], 2)
temp.sort_values('rate', ascending=False)

[train]

       Wdft_RegionIdentifier   rate
 10.0                1800105  20.18
 11.0                1347828  15.11
 3.0                 1295892  14.53
 1.0                 1232258  13.81
 15.0                1017591  11.41
 7.0                  597297   6.70
NaN                   303451   3.40
 8.0                  276029   3.09
 13.0                 225130   2.52
 5.0                  205372   2.30
 12.0                 163711   1.84
 6.0                  158163   1.77
 4.0                  135567   1.52
 9.0                   79882   0.90
 2.0                   79385   0.89
 14.0                   3822   0.04

In [162]:
print("[test]")
temp = test[col].value_counts(dropna=False).to_frame()
temp['rate'] = np.around(100 * test[col].value_counts(dropna=False) / test.shape[0], 2)
temp.sort_values('rate', ascending=False)

[test]

       Wdft_RegionIdentifier   rate
 10.0                1451816  18.49
 11.0                1264670  16.10
 3.0                 1253395  15.96
 1.0                 1109642  14.13
 15.0                 787767  10.03
 7.0                  601077   7.65
NaN                   302857   3.86
 8.0                  228934   2.92
 13.0                 199668   2.54
 5.0                  163548   2.08
 12.0                 127190   1.62
 6.0                  127072   1.62
 4.0                   94853   1.21
 2.0                   63098   0.80
 9.0                   60802   0.77
 14.0                  16864   0.21

In [163]:
table = train.groupby(col)['HasDetections'].sum().to_frame()
table['cnt'] = train.groupby(col)['HasDetections'].count()
table['rate'] = np.around((table.HasDetections / table.cnt) * 100, 2)
table.sort_values('HasDetections', ascending=False)

                       HasDetections      cnt   rate
Wdft_RegionIdentifier
10.0                        916641.0  1800105  50.92
11.0                        678230.0  1347828  50.32
1.0                         659826.0  1232258  53.55
3.0                         638119.0  1295892  49.24
15.0                        474349.0  1017591  46.61
7.0                         299335.0   597297  50.11
8.0                         135824.0   276029  49.21
13.0                        107481.0   225130  47.74
5.0                          99113.0   205372  48.26
12.0                         77151.0   163711  47.13
6.0                          75333.0   158163  47.63
4.0                          64536.0   135567  47.60
9.0                          36687.0    79882  45.93
2.0                          36267.0    79385  45.68
14.0                          2077.0     3822  54.34